Repository KarmaKamikaze/HotelPriceScout, pull requests merged in 2021-11, with the labels that each got.

#48 Vaterpas
  HotelPriceScout/Pages/PriceMeterGenerator.cs
  HotelPriceScout/Pages/PriceThermometerComponent.razor
  HotelPriceScout/Pages/Prices.cs
  HotelPriceScout/Shared/NavMenu.razor
Labels: enhancement

#50 Feature/css cal
  HotelPriceScout/Data/Interface/Dashbord.cs
  HotelPriceScout/HotelPriceScout.csproj
  HotelPriceScout/Pages/Index.razor
  HotelPriceScout/Pages/Index.razor.css
  HotelPriceScout/Pages/PriceMeterGenerator.cs
  HotelPriceScout/Pages/PriceThermometerComponent.razor
  HotelPriceScout/Pages/Prices.cs
  HotelPriceScout/Shared/MainLayout.razor
  HotelPriceScout/Shared/MainLayout.razor.css
  HotelPriceScout/Shared/NavMenu.razor
  HotelPriceScout/Startup.cs
Labels: enhancement

#52 Comment changes and removal of useless settings
  HotelPriceScout/Pages/Settings.razor
  HotelPriceScout/Pages/_Host.cshtml
Labels: enhancement

#56 Feature/price thermometer css
  HotelPriceScout/Pages/PriceThermometerComponent.razor
Labels: enhancement

#62 30 dummy lines i db
  database.sqlite
Labels: enhancement

#65 Buttons now keep their states when switching pages
  HotelPriceScout/Pages/Settings.razor
Labels: enhancement

#69 Values are saved on button clicks
  HotelPriceScout/Pages/Settings.razor
Labels: enhancement

#71 Db inster method done
  DataAccessLibrary/SqliteDataAccess.cs
Labels: enhancement

#72 User assurance and nav bar updates
  HotelPriceScout/Pages/Settings.razor
  HotelPriceScout/Shared/MainLayout.razor
  HotelPriceScout/Shared/NavMenu.razor
  HotelPriceScout/Shared/NavMenu.razor.css
Labels: enhancement

#80 Update database.sqlite
  database.sqlite
Labels: enhancement

#83 blanking out cells with no data in the calendar
  HotelPriceScout/Pages/Index.razor
Labels: enhancement

#81 Update SqliteDataAccess.cs
  DataAccessLibrary/SqliteDataAccess.cs
Labels: enhancement

#84 Feature/automate calendar
  DataAccessLibrary/MarketPriceModel.cs
  DataAccessLibrary/SqliteDataAccess.cs
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Data/Interface/Dashbord.cs
  HotelPriceScout/Pages/Index.razor
  HotelPriceScout/Program.cs
Labels: enhancement

#87 Feature/automate you prices
  DataAccessLibrary/MarketPriceModel.cs
  DataAccessLibrary/SqliteDataAccess.cs
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/Index.razor
Labels: enhancement

#89 Feature/cal fix
  DataAccessLibrary/MarketPriceModel.cs
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/Index.razor
  database.sqlite
Labels: enhancement

#91 masser af desgin updates
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/Index.razor
  HotelPriceScout/Pages/Index.razor.css
  database.sqlite
Labels: enhancement

#104 Setting for 0 notifications added
  HotelPriceScout/Pages/Settings.razor
Labels: enhancement

#105 Settings manager class added
  HotelPriceScout/Data/Interface/SettingsManager.cs
  HotelPriceScout/Pages/Settings.razor
Labels: enhancement

#106 Feature/unit testing
  HotelPriceScout.sln
  Tests/Properties/AssemblyInfo.cs
  Tests/Tests.csproj
  Tests/UnitTest1.cs
  Tests/packages.config
Labels: enhancement

#129 mange forbedringer til front end, mest kalenderen
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/Index.razor
  HotelPriceScout/Pages/Index.razor.css
Labels: enhancement

#130 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#151 Feature/smallest fix this year
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/Index.razor.css
Labels: enhancement

#175 Gennemsint er det samme i kalender og termometer
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/PriceMeterGenerator.cs
Labels: bug

#177 Feature/dashboard animation fix
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/DashboardPage.razor.css
Labels: enhancement, Front-end

#178 Redirect modal window
  HotelPriceScout/Data/Interface/SettingsManager.cs
  HotelPriceScout/Pages/Settings.razor
Labels: enhancement, Front-end

#188 small css changes to dropdown
  HotelPriceScout/Pages/Settings.razor
Labels: enhancement, Front-end

#189 Create pages.yml
  .github/workflows/pages.yml
Labels: to investigate

#195 SetScoutSettings
  HotelPriceScout/Data/Interface/SettingsManager.cs
  HotelPriceScout/Pages/Settings.razor
Labels: enhancement, Front-end

#196 Feature/fix termometer
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/DashboardPage.razor
Labels: bug

#205 monke
  HotelPriceScout/Data/Model/Comparator.cs
  HotelPriceScout/Pages/DashboardPage.razor
Labels: bug

#209 Dashboard inherit
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Pages/DashboardPage.razor
Labels: bug, retard, Front-end

#217 Feature/thermometer fix
  HotelPriceScout/Data/Interface/PriceMeterGenerator.cs
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/DashboardPage.razor.css
Labels: enhancement, Front-end

#219 knapper virker igen altid
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/DashboardPage.razor.css
Labels: enhancement, Front-end

#218 Feature/settings page clean up
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Data/Interface/SettingsManager.cs
  HotelPriceScout/Pages/Settings.razor
  HotelPriceScout/Startup.cs
Labels: bug, Front-end

#221 Feature/dashboard unit test
  HotelPriceScout/Data/Function/PseudoScraper.cs
  Tests/DashboardTest.cs
  Tests/SettingsManagerTest.cs
Labels: test

#228 Feature/css fokus fix
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Data/Interface/IDashboard.cs
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/DashboardPage.razor.css
Labels: bug, enhancement, Front-end

#229 Feature/bool clean up
  HotelPriceScout/Data/Interface/SettingsManager.cs
  HotelPriceScout/Pages/Settings.razor
Labels: enhancement, Front-end

#232 Feature/dashboard popup
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Data/Interface/IDashboard.cs
  HotelPriceScout/Data/Interface/WarningMessage.cs
  HotelPriceScout/HotelPriceScout.csproj
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/wwwroot/css/bootstrap/bootstrap.min.css
  database.sqlite
Labels: bug

#241 Feature/home button fix
  HotelPriceScout/Shared/MainLayout.razor
Labels: bug, Front-end

#243 Feature/css dropdown
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/DashboardPage.razor.css
Labels: enhancement, Front-end

#246 Feature/fix modal window size
  HotelPriceScout/Pages/Settings.razor
  HotelPriceScout/Pages/Settings.razor.css
Labels: enhancement, Front-end
