Repository KarmaKamikaze/HotelPriceScout, pull requests merged in 2021-12, with the labels that each got.

#259 done
  HotelPriceScout/Data/Interface/PriceMeterGenerator.cs
  HotelPriceScout/Pages/DashboardPage.razor
Labels: enhancement, Front-end

#263 Feature/settings clarification
  HotelPriceScout/Pages/Settings.razor
  HotelPriceScout/Pages/Settings.razor.css
Labels: enhancement, Front-end

#264 ID weekdays nu er det væk
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/DashboardPage.razor.css
Labels: enhancement, Front-end

#268 Feature/bigchange
  HotelPriceScout/Pages/DashboardPage.razor
Labels: enhancement

#275 Feature/remove year
  HotelPriceScout/Data/Interface/Dashboard.cs
Labels: enhancement, Front-end

#295 removed memberdata
  Tests/TimeKeeperTest.cs
Labels: test

#296 Feature/descriptive UI text
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/Settings.razor
  HotelPriceScout/Shared/MainLayout.razor
Labels: enhancement, Front-end

#298 Feature/tab removed
  HotelPriceScout/Data/Interface/Dashboard.cs
Labels: enhancement

#299 New dashboard ss in README
  .github/images/dashboardPageNew.PNG
Labels: documentation

#300 Update README.md
  README.md
Labels: documentation

#315 Feature/e2e dashboard
  DataAccessLibrary/ISqliteDataAccess.cs
  DataAccessLibrary/PriceModel.cs
  DataAccessLibrary/SqliteDataAccess.cs
  HotelPriceScout/Data/Interface/IDashboard.cs
  HotelPriceScout/Data/Interface/PriceMeterGenerator.cs
  HotelPriceScout/Data/Model/Comparator.cs
  HotelPriceScout/Data/Model/IComparator.cs
  HotelPriceScout/Data/Model/IScout.cs
  HotelPriceScout/Data/Model/Scout.cs
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/DashboardPage.razor.css
  HotelPriceScout/Shared/MainLayout.razor
  Tests/DashboardPageE2ETests.cs
  Tests/SettingsPageTest.cs
Labels: test, Back-end

#317 Feature/clean up
  DataAccessLibrary/ISqliteDataAccess.cs
  DataAccessLibrary/PriceModel.cs
  DataAccessLibrary/SqliteDataAccess.cs
  HotelPriceScout/Data/Function/IDataScraper.cs
  HotelPriceScout/Data/Function/ITimeKeeper.cs
  HotelPriceScout/Data/Function/ITimeMonitor.cs
  HotelPriceScout/Data/Function/PseudoScraper.cs
  HotelPriceScout/Data/Function/TimeKeeper.cs
  HotelPriceScout/Data/Function/TimeMonitor.cs
  HotelPriceScout/Data/Interface/Dashboard.cs
  HotelPriceScout/Data/Interface/IDashboard.cs
  HotelPriceScout/Data/Interface/PriceMeterGenerator.cs
  HotelPriceScout/Data/Interface/ScoutSharedService.cs
  HotelPriceScout/Data/Interface/SettingsManager.cs
  HotelPriceScout/Data/Interface/WarningMessage.cs
  HotelPriceScout/Data/Model/BookingSite.cs
  HotelPriceScout/Data/Model/Comparator.cs
  HotelPriceScout/Data/Model/Hotel.cs
  HotelPriceScout/Data/Model/IComparator.cs
  HotelPriceScout/Data/Model/IScout.cs
  HotelPriceScout/Data/Model/RoomType.cs
  HotelPriceScout/Data/Model/RoomTypePrice.cs
  HotelPriceScout/Data/Model/Scout.cs
  HotelPriceScout/HotelPriceScout.csproj
  HotelPriceScout/Pages/DashboardPage.razor
  HotelPriceScout/Pages/Settings.razor
  HotelPriceScout/Program.cs
  HotelPriceScout/Shared/MainLayout.razor
  HotelPriceScout/Startup.cs
  HotelPriceScout/appsettings.Development.json
  README.md
  Tests/BookingSiteTest.cs
  Tests/ComparatorTest.cs
  Tests/DashboardPageE2ETests.cs
  Tests/DashboardTest.cs
  Tests/HotelTest.cs
  Tests/IndexE2ETests.cs
  Tests/PseudoScraperTest.cs
  Tests/RoomTypePriceTest.cs
  Tests/RoomTypeTest.cs
  Tests/ScoutTest.cs
  Tests/SettingsManagerTest.cs
  Tests/SettingsPageE2ETests.cs
  Tests/SettingsPageTest.cs
  Tests/TimeMonitorTest.cs
  database.sqlite
Labels: Front-end, Back-end

#321 Add bold class to AverageMarketPrice
  HotelPriceScout/HotelPriceScout.csproj
  HotelPriceScout/Pages/DashboardPage.razor
  global.json
Labels: bug
